### ISSUE TITLE
Insert pandas Dataframe code - df_data_2

### ISSUE THREAD

**Issue by tylernd27** [IBM/pixiedust-facebook-analysis#74]
When inserting code for pandas dataframe of example facebook data the dataframe is given the name `df_data_2` and in the next cell we try to change `df = df_data_1` 

Same with inserting credentials code. Sometimes is entered with number other than 1.

**Comment by markstur** [comment]
this is explained in the readme

**Comment by tylernd27** [comment]
I know - and that's why we include the follow up cell, but wanted to see if there was anything cleaner.

**Comment by markstur** [comment]
ok, yes... It would be great if there's a better way.  I think it actually avoids using df_data_1 and credentials_1 because it knows we are already using it  :(   
ultimately we don't control it. We could check for any df_data_* and credentials_* variables (w/ some deep python I think) but if that ever failed it'd be more confusing.
Mostly just finding something easy to explain and catch mistakes is what I was looking for.

**Comment by tylernd27** [comment]
I agree - this is the easiest way to go about it for now. Not worth the effort.
